[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60 --log-level info'

